### ISSUE TITLE
Lots of samples doesn't work because of changes in spec.

### ISSUE THREAD

**Issue by BS-Harou** [borismus/webaudioapi.com#6]
Especially the change from constants to string enums caused a lot of samples to not work properly.

**Comment by borismus** [comment]
Which samples are broken, and which browser are you testing on? Thanks!

**Comment by amundo** [comment]
I went through the examples in Firefox 41.0b1, and here are my results:

works
Metering

works
Frequency Response

works
Microphone

works
Oscillator

works
Procedural sound

works
Rapidly played sounds

works
Drumkit Rhythm

TypeError: this.impulseResponseBuffer is undefined room-effects-sample.js:50:3
Room Effects

works
Script Processor Node

doesn’t work, no console error
Spatialized audio in 2D

uncaught exception: out of memory
Tremolo with timing curves and oscillators

TypeError: this.buffer is undefined
Visualizer

doesn’t work, no console error
Volume Control

**Comment by borismus** [comment]
Ok, fixed and verified in Firefox and Chrome. Let me know if you still see issues.
